In [7]:
# Import Libraries
import pandas as pd
import numpy as np
import panel as pn
pn.extension(comms='vscode') #this is so the widgets will show on VS code
pn.extension('tabulator')
import hvplot.pandas

pn.pane.Markdown("Hello")

BokehModel(combine_events=True, render_bundle={'docs_json': {'3742a3e4-0476-412b-b7f7-864b584af1f8': {'defs': â€¦

Markdown(str)

In [12]:
#Importing dummy data. 
df = pd.read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv") #This portion of the code should be provided by front end to know what we should be plotting exactly! (or data aquisition?)
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1850,AFG,3752993.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.121,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1851,AFG,3769828.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.118,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1852,AFG,3787706.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.116,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1853,AFG,3806634.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.115,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1854,AFG,3825655.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.114,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46518,Zimbabwe,2017,ZWE,14751101.0,2.194784e+10,0.469,0.032,9.596,-0.937,-8.899,...,NaN,0.0,0.0,0.219,0.026,NaN,115.59,28.30,0.910,9.486
46519,Zimbabwe,2018,ZWE,15052191.0,2.271535e+10,0.558,0.037,11.795,2.199,22.920,...,NaN,0.0,0.0,0.211,0.033,NaN,118.22,30.83,0.771,6.537
46520,Zimbabwe,2019,ZWE,15354606.0,NaN,0.570,0.037,11.115,-0.681,-5.772,...,NaN,0.0,0.0,0.183,0.030,NaN,117.96,30.53,0.978,8.795
46521,Zimbabwe,2020,ZWE,15669663.0,NaN,0.570,0.036,10.608,-0.507,-4.559,...,NaN,0.0,0.0,0.194,0.030,NaN,NaN,NaN,1.006,9.481
46522,Zimbabwe,2021,ZWE,15993525.0,NaN,0.570,0.036,11.296,0.688,6.488,...,NaN,0.0,0.0,0.190,0.030,NaN,NaN,NaN,NaN,NaN

In [13]:
df[df['country'] == 'China'] #This is how you choose from all available countries in the df (from country columns)

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_cumulative_other_co2,share_global_flaring_co2,share_global_gas_co2,share_global_luc_co2,share_global_oil_co2,share_global_other_co2,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
8819,China,1850,CHN,4.098216e+08,3.534960e+11,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.629,NaN,NaN,NaN,NaN,NaN,NaN
8820,China,1851,CHN,4.076856e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.232,NaN,NaN,NaN,NaN,NaN,NaN
8821,China,1852,CHN,4.048401e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.733,NaN,NaN,NaN,NaN,NaN,NaN
8822,China,1853,CHN,4.012912e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.473,NaN,NaN,NaN,NaN,NaN,NaN
8823,China,1854,CHN,3.977733e+08,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,8.036,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8986,China,2017,CHN,1.410276e+09,1.757508e+13,758.185,0.538,10011.107,246.128,2.521,...,49.603,0.746,6.807,5.391,11.685,56.148,11385.48,12035.27,-860.915,-8.600
8987,China,2018,CHN,1.417069e+09,1.815162e+13,786.745,0.555,10353.877,342.770,3.424,...,49.848,0.813,7.641,5.886,12.233,56.711,11821.66,12471.09,-727.290,-7.024
8988,China,2019,CHN,1.421864e+09,NaN,826.876,0.582,10740.996,387.119,3.739,...,50.117,0.867,8.240,5.800,12.634,57.806,12055.41,12705.09,-781.827,-7.279
8989,China,2020,CHN,1.424930e+09,NaN,858.233,0.602,10956.213,215.217,2.004,...,50.362,1.256,9.103,7.270,14.544,57.893,NaN,NaN,-922.811,-8.423
8990,China,2021,CHN,1.425894e+09,NaN,852.961,0.598,11472.368,516.155,4.711,...,50.593,1.123,9.769,8.317,14.474,57.924,NaN,NaN,NaN,NaN

## (0) Some minor data preprocessing

In [14]:
# Fill NAs with 0s and create GDP per capita column
df = df.fillna(0)
df['gdp_per_capita'] = np.where(df['population']!= 0, df['gdp']/ df['population'], 0)

In [15]:
# Make DataFrame Pipeline Interactive ####### IMPERATIVE!!!!! #######
idf = df.interactive()

## (1) CO2 emission over time by continent

In [16]:
# Define Panel widgets 
# I think front end can be the one to develop which widgets/interactive plots to add? Also need to communicate with UX about this
year_slider = pn.widgets.IntSlider(name='Year slider', start=1750, end=2020, step=5, value=1850)
year_slider

BokehModel(combine_events=True, render_bundle={'docs_json': {'055d7e35-b697-45ff-9b4c-47bd07fc0e89': {'defs': â€¦

IntSlider(end=2020, name='Year slider', start=1750, step=5, value=1850)